CREATE OR REPLACE PACKAGE ROUTING_UTIL
AS
  PROCEDURE INSERT_RULE(
      P_NAME           VARCHAR2 ,
      P_DESCRIPTION    VARCHAR2,
      P_FOR_ROLE       VARCHAR2,
      P_FROM_STATUS    VARCHAR2,
      P_TO_STATUS      VARCHAR2,
      P_READY_TO_PRINT VARCHAR2,
      P_FOR_ACCEPTOR   VARCHAR2,
      P_FOR_AUTHOR     VARCHAR2,
      P_FOR_MANAGER    VARCHAR2,
      P_PICK_ACCEPTOR  VARCHAR2,
      P_PICK_MANAGER   VARCHAR2,
      P_CLEAR_MANAGER  VARCHAR2,
      P_CLEAR_ACC	   VARCHAR2,
      P_ACC_STATE VARCHAR2,
      P_ACC_STATE_CODE VARCHAR2,
      P_FROM_ACC_STATE VARCHAR2,
      P_APPLY_ACC VARCHAR2,
      P_RULE_CODE VARCHAR2
    );
  FUNCTION GET_STATUS_ID(
      P_STATUS VARCHAR2)
    RETURN NUMBER;
  FUNCTION IS_EMPTY(
    P_STR VARCHAR2)
  RETURN NUMBER;
  FUNCTION GET_ACC_STATUS_ID(
    P_STATUS VARCHAR2)
  RETURN NUMBER;

  PROCEDURE ADD_RULE_VALIDATION(
    P_RULE_CODE VARCHAR2,
    P_VALIDATION_CODE VARCHAR2
  );
END ROUTING_UTIL;
/


CREATE OR REPLACE PACKAGE BODY ROUTING_UTIL
AS
FUNCTION GET_STATUS_ID(
    P_STATUS VARCHAR2)
  RETURN NUMBER
IS
  L_ID NUMBER;
BEGIN
  SELECT
    DICT_ID
  INTO
    L_ID
  FROM
    DICTIONARIES
  WHERE
    DICTIONARY_NAME = 'ARTICLE_STATUS'
  AND CODE          = P_STATUS;
  RETURN L_ID;
END;

FUNCTION GET_ACC_STATUS_ID(
    P_STATUS VARCHAR2)
  RETURN NUMBER
IS
  L_ID NUMBER;
BEGIN
  SELECT
    DICT_ID
  INTO
    L_ID
  FROM
    DICTIONARIES
  WHERE
    DICTIONARY_NAME = 'ACCEPTOR_STATUS'
  AND CODE          = P_STATUS;
  RETURN L_ID;
  EXCEPTION
    WHEN NO_DATA_FOUND 
      THEN RETURN NULL;
END;

FUNCTION IS_EMPTY(
    P_STR VARCHAR2)
  RETURN NUMBER
IS
BEGIN
  RETURN
  CASE
  WHEN P_STR IS NULL THEN
    0
  WHEN P_STR ='' THEN
    0
  ELSE
    1
  END;
END;
PROCEDURE INSERT_RULE(
    P_NAME           VARCHAR2 ,
    P_DESCRIPTION    VARCHAR2,
    P_FOR_ROLE       VARCHAR2,
    P_FROM_STATUS    VARCHAR2,
    P_TO_STATUS      VARCHAR2,
    P_READY_TO_PRINT VARCHAR2,
    P_FOR_ACCEPTOR   VARCHAR2,
    P_FOR_AUTHOR     VARCHAR2,
    P_FOR_MANAGER    VARCHAR2,
    P_PICK_ACCEPTOR  VARCHAR2,
    P_PICK_MANAGER   VARCHAR2,
    P_CLEAR_MANAGER  VARCHAR2,
    P_CLEAR_ACC	   VARCHAR2,
    P_ACC_STATE VARCHAR2,
      P_ACC_STATE_CODE VARCHAR2,
      P_FROM_ACC_STATE VARCHAR2,
      P_APPLY_ACC VARCHAR2,
      P_RULE_CODE VARCHAR2
    )
IS
BEGIN
  INSERT
  INTO
    ROUTING_RULES
    (
      RULE_ID,
      NAME,
      DESCRIPTION,
      FOR_ROLE_NAME,
      FROM_STATUS,
      TO_STATUS,
      READY_TO_PRINT,
      FOR_ACCEPTOR,
      FOR_AUTHOR,
      FOR_MANAGER,
      PICK_ACCEPTORS,
      PICK_MANAGER,
      CLEAR_MANAGER,
      CLEAR_ACCEPTORS,
      IS_ACTIVE,
      SET_ACCEPTOR_STATUS,
      ACCEPT_STATUS,
      FROM_ACCEPTORS_STATE,
      APPLY_ACCEPTORS_STATE,
      RULE_CODE
    )
    VALUES
    (
      ROUTING_RULES_SEQ.NEXTVAL,
      P_NAME,
      P_DESCRIPTION,
      P_FOR_ROLE,
      GET_STATUS_ID(P_FROM_STATUS),
      GET_STATUS_ID(P_TO_STATUS),
      IS_EMPTY(P_READY_TO_PRINT),
      IS_EMPTY(P_FOR_ACCEPTOR),
      IS_EMPTY(P_FOR_AUTHOR),
      IS_EMPTY(P_FOR_MANAGER),
      IS_EMPTY(P_PICK_ACCEPTOR),
      IS_EMPTY(P_PICK_MANAGER),
      IS_EMPTY(P_CLEAR_MANAGER),
      IS_EMPTY(P_CLEAR_ACC),
      1,
      IS_EMPTY(P_ACC_STATE),
      GET_ACC_STATUS_ID(P_ACC_STATE_CODE),
      IS_EMPTY(P_FROM_ACC_STATE),
      IS_EMPTY(P_APPLY_ACC),
      P_RULE_CODE
    );
END INSERT_RULE;

PROCEDURE ADD_RULE_VALIDATION(
    P_RULE_CODE VARCHAR2,
    P_VALIDATION_CODE VARCHAR2
  ) IS
BEGIN
  INSERT INTO RULES_VALIDATIONS(RULE_ID, DICT_ID)
  VALUES (
    (SELECT RULE_ID FROM ROUTING_RULES WHERE RULE_CODE = P_RULE_CODE),
    (SELECT DICT_ID FROM DICTIONARIES WHERE CODE = P_VALIDATION_CODE AND DICTIONARY_NAME ='VALIDATION_RULE')
  );
END;
END ROUTING_UTIL;


/
/*
  Skrypt insertujacy statusy artykułów z konfiguracją
*/
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','ACC','Zaakceptowany',null,null,null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','CPL','Kompletny',null,null,null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','NEW','Zarejestrowany','INITIAL','DELETE',null,'ADD_VER',null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','NOT_ACC','Niezaakceptowany',null,null,null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','PACC','Przekazany do recenzji',null,null,'ADD_ACC_VER',null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','PMNG','Przekazany do edytora',null,null,null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','PRINTED','Wydrukowany',null,null,'FOR_PRINT',null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','REJ','Odrzucony',null,'DELETE',null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','RET','Cofnięty',null,null,null,'ADD_VER',null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','TO_PRINT','Gotowy do wydruku',null,null,'FOR_PRINT',null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','WARN_ACC','Zaakceptowany z poprawkami',null,null,null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','PMNG_IMPR','Przekazany do edytora po poprawkach',null,null,null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','PACC_IMPR','Przekazany do recenzji po poprawkach',null,null,'ADD_ACC_VER',null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ARTICLE_STATUS','RET_IMPR','Cofnięty do poprawy',null,null,null,'ADD_VER',null,null,null);

/*
  Statusy akceptujących
*/

insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ACCEPTOR_STATUS','ACC','Zaakceptowane',null,null,null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ACCEPTOR_STATUS','ERR','Niezaakceptowane',null,null,null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'ACCEPTOR_STATUS','WARN_ACC','Do poprawy',null,null,null,null,null,null,null);

/*
  Parametry systemowe
*/

insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE2) values (DICTIONARY_SEQ.nextval, 'SYSTEM_PARAM','ARTICLE_DIR','Ścieżka zapisu artykułów','C:/');
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE2) values (DICTIONARY_SEQ.nextval, 'SYSTEM_PARAM','TMP_DIR','Ścieżka tymczasowego zapisu artykułów','C:/');

/*
  definicje walidacji
*/

insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'VALIDATION_RULE','ADD_VER','Nie dodano żadnej wersji',null,null,null,null,3,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'VALIDATION_RULE','PICK_ACC','Należy wybrać przynajmniej 1. recenzenta',null,null,null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'VALIDATION_RULE','PICK_MNG','Nie wybrano zarządzającego',null,null,null,null,null,null,null);
insert into DICTIONARIES(DICT_ID, DICTIONARY_NAME,CODE,DESCRIPTION,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,NUM_ATTR1,NUM_ATTR2,PARENT_CODE) values (DICTIONARY_SEQ.nextval, 'VALIDATION_RULE','TOO_MANY_ACC','Przekroczono maksymalną ilość recenzentów. Max: 5',null,null,null,null,null,5,null);

/*
  reguły procesowe
*/

exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'CPL_NEW',P_NAME=>'Kompletuj',P_DESCRIPTION=>'Kompletuj',P_FOR_ROLE=>'AUTHOR',P_FROM_STATUS=>'NEW',P_TO_STATUS=>'CPL',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'x',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'x',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'RET_CPL',P_NAME=>'Cofnij',P_DESCRIPTION=>'Cofnij',P_FOR_ROLE=>'AUTHOR',P_FROM_STATUS=>'CPL',P_TO_STATUS=>'RET',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'x',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'x',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'REJ_0001',P_NAME=>'Odrzuć',P_DESCRIPTION=>'Odrzuć',P_FOR_ROLE=>'AUTHOR',P_FROM_STATUS=>'RET',P_TO_STATUS=>'REJ',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'x',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'CPL_RET',P_NAME=>'Kompletuj',P_DESCRIPTION=>'Kompletuj',P_FOR_ROLE=>'AUTHOR',P_FROM_STATUS=>'RET',P_TO_STATUS=>'CPL',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'x',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'x',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PMNG',P_NAME=>'Przekaż do edytora',P_DESCRIPTION=>'Przekaż do edytora',P_FOR_ROLE=>'AUTHOR',P_FROM_STATUS=>'CPL',P_TO_STATUS=>'PMNG',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'x',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'CHANGE_MNG',P_NAME=>'Zmień edytora',P_DESCRIPTION=>'Zmień edytora',P_FOR_ROLE=>'ARTICLE_MANAGER',P_FROM_STATUS=>'PMNG',P_TO_STATUS=>'PMNG',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'x',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'x',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PACC',P_NAME=>'Przekaż do recenzji',P_DESCRIPTION=>'Przekaż do recenzji',P_FOR_ROLE=>'ARTICLE_MANAGER',P_FROM_STATUS=>'PMNG',P_TO_STATUS=>'PACC',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'x',P_PICK_ACCEPTOR=>'x',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PACC_ACCCEPT1',P_NAME=>'Akceptuj',P_DESCRIPTION=>'Akceptuj',P_FOR_ROLE=>'ACCEPTOR',P_FROM_STATUS=>'PACC',P_TO_STATUS=>'PACC',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'x',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'x',P_ACC_STATE_CODE=>'ACC',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PACC_REJECT',P_NAME=>'Odrzuć',P_DESCRIPTION=>'Odrzuć',P_FOR_ROLE=>'ACCEPTOR',P_FROM_STATUS=>'PACC',P_TO_STATUS=>'PACC',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'x',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'x',P_ACC_STATE_CODE=>'ERR',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PACC_TO_IMPR',P_NAME=>'Do poprawy',P_DESCRIPTION=>'Do poprawy',P_FOR_ROLE=>'ACCEPTOR',P_FROM_STATUS=>'PACC',P_TO_STATUS=>'PACC',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'x',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'x',P_ACC_STATE_CODE=>'WARN_ACC',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'MNG_REJ',P_NAME=>'Odrzucony',P_DESCRIPTION=>'Odrzucony',P_FOR_ROLE=>'ARTICLE_MANAGER',P_FROM_STATUS=>'PACC',P_TO_STATUS=>'REJ',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'x',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'x',P_APPLY_ACC=>'x');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'MNG_RET_TO_IMPR',P_NAME=>'Do poprawy',P_DESCRIPTION=>'Do poprawy',P_FOR_ROLE=>'ARTICLE_MANAGER',P_FROM_STATUS=>'PACC',P_TO_STATUS=>'RET_IMPR',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'x',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'x',P_APPLY_ACC=>'x');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'MNG_ACC',P_NAME=>'Zaakceptowany',P_DESCRIPTION=>'Zaakceptowany',P_FOR_ROLE=>'ARTICLE_MANAGER',P_FROM_STATUS=>'PACC',P_TO_STATUS=>'TO_PRINT',P_READY_TO_PRINT=>'x',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'x',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'x',P_APPLY_ACC=>'x');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PRINT',P_NAME=>'Drukuj',P_DESCRIPTION=>'Drukuj',P_FOR_ROLE=>'PRINTER',P_FROM_STATUS=>'TO_PRINT',P_TO_STATUS=>'PRINTED',P_READY_TO_PRINT=>'x',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PMNG_IMPR',P_NAME=>'Przekaż po poprawkach',P_DESCRIPTION=>'Przekaż po poprawkach',P_FOR_ROLE=>'AUTHOR',P_FROM_STATUS=>'RET_IMPR',P_TO_STATUS=>'PMNG_IMPR',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'x',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PACC_IMPR',P_NAME=>'Przekaż do recenzji',P_DESCRIPTION=>'Przekaż do recenzji',P_FOR_ROLE=>'ARTICLE_MANAGER',P_FROM_STATUS=>'PMNG_IMPR',P_TO_STATUS=>'PACC_IMPR',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'x',P_PICK_ACCEPTOR=>'x',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PACC_ACCCEPT_IMPR',P_NAME=>'Akceptuj',P_DESCRIPTION=>'Akceptuj',P_FOR_ROLE=>'ACCEPTOR',P_FROM_STATUS=>'PACC_IMPR',P_TO_STATUS=>'PACC_IMPR',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'x',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'x',P_ACC_STATE_CODE=>'ACC',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PACC_REJECT_IMPR',P_NAME=>'Odrzuć',P_DESCRIPTION=>'Odrzuć',P_FOR_ROLE=>'ACCEPTOR',P_FROM_STATUS=>'PACC_IMPR',P_TO_STATUS=>'PACC_IMPR',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'x',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'x',P_ACC_STATE_CODE=>'ERR',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'PACC_TO_IMPR_IMPR',P_NAME=>'Do poprawy',P_DESCRIPTION=>'Do poprawy',P_FOR_ROLE=>'ACCEPTOR',P_FROM_STATUS=>'PACC_IMPR',P_TO_STATUS=>'PACC_IMPR',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'x',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'x',P_ACC_STATE_CODE=>'WARN_ACC',P_FROM_ACC_STATE=>'',P_APPLY_ACC=>'');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'MNG_REJ_IMPR',P_NAME=>'Odrzucony',P_DESCRIPTION=>'Odrzucony',P_FOR_ROLE=>'ARTICLE_MANAGER',P_FROM_STATUS=>'PACC_IMPR',P_TO_STATUS=>'REJ',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'x',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'x',P_APPLY_ACC=>'x');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'MNG_RET_TO_IMPR2',P_NAME=>'Do poprawy',P_DESCRIPTION=>'Do poprawy',P_FOR_ROLE=>'ARTICLE_MANAGER',P_FROM_STATUS=>'PACC_IMPR',P_TO_STATUS=>'RET_IMPR',P_READY_TO_PRINT=>'',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'x',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'x',P_APPLY_ACC=>'x');
exec ROUTING_UTIL.insert_rule(P_RULE_CODE=>'MNG_ACC_IMPR',P_NAME=>'Zaakceptowany po poprawkach',P_DESCRIPTION=>'Zaakceptowany po poprawkach',P_FOR_ROLE=>'ARTICLE_MANAGER',P_FROM_STATUS=>'PACC_IMPR',P_TO_STATUS=>'TO_PRINT',P_READY_TO_PRINT=>'x',P_FOR_ACCEPTOR=>'',P_FOR_AUTHOR=>'',P_FOR_MANAGER=>'x',P_PICK_ACCEPTOR=>'',P_PICK_MANAGER=>'',P_CLEAR_MANAGER=>'',P_CLEAR_ACC=>'',P_ACC_STATE=>'',P_ACC_STATE_CODE=>'',P_FROM_ACC_STATE=>'x',P_APPLY_ACC=>'x');

/*
  przypięcia walidacji
*/

exec ROUTING_UTIL.ADD_RULE_VALIDATION(P_RULE_CODE=>'CPL_NEW',P_VALIDATION_CODE=>'PICK_MNG');
exec ROUTING_UTIL.ADD_RULE_VALIDATION(P_RULE_CODE=>'CPL_NEW',P_VALIDATION_CODE=>'ADD_VER');
exec ROUTING_UTIL.ADD_RULE_VALIDATION(P_RULE_CODE=>'CPL_RET',P_VALIDATION_CODE=>'PICK_MNG');
exec ROUTING_UTIL.ADD_RULE_VALIDATION(P_RULE_CODE=>'CPL_RET',P_VALIDATION_CODE=>'ADD_VER');
exec ROUTING_UTIL.ADD_RULE_VALIDATION(P_RULE_CODE=>'PACC',P_VALIDATION_CODE=>'PICK_ACC');
exec ROUTING_UTIL.ADD_RULE_VALIDATION(P_RULE_CODE=>'PACC_IMPR',P_VALIDATION_CODE=>'TOO_MANY_ACC');
exec ROUTING_UTIL.ADD_RULE_VALIDATION(P_RULE_CODE=>'PACC',P_VALIDATION_CODE=>'TOO_MANY_ACC');
exec ROUTING_UTIL.ADD_RULE_VALIDATION(P_RULE_CODE=>'PACC_IMPR',P_VALIDATION_CODE=>'PICK_ACC');
exec ROUTING_UTIL.ADD_RULE_VALIDATION(P_RULE_CODE=>'CHANGE_MNG',P_VALIDATION_CODE=>'PICK_MNG');


commit;
